### PR TITLE
Add funds page styling

### PR DESCRIPTION
**Pull request by PowersOfEight**
#### Currently, this PR:

* Removes some of the labels and redundant inputs
* Fixes transition for input button
* Overall Design is much cleaner (see photo)

image

### CODE REVIEW

**Comment by wnorowskie** [comment]
Based on feedback of other pages, I would introduce even more spacing between elements or add more elements so there is not as much empty white space on the bottom.

**Comment by wnorowskie** [comment]
Also just double check that the ActionButton is not being used elsewhere, where the change might cause issues.

**Comment by PowersOfEight** [comment]
### Added some vertical spacing to address feedback

* Here's how it looks upon load:
image

* Here's what it looks like when inputting additional balance:
image

**Comment by PowersOfEight** [comment]
### This is now rolled into PR 31

**Pull request closed without merging**
